services:
  netpilot_server:
    build: .
    container_name: netpilot_server
    ports:
      - "5000:5000"
    networks:
      - default
    cap_add:
      - NET_ADMIN  # Required for ARP scanning
