"""add scheduled_tasks table

Revision ID: 346d0f1d4dc8
Revises: fix_foreign_keys
Create Date: 2025-08-20 12:20:02.903911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '346d0f1d4dc8'
down_revision: Union[str, None] = 'fix_foreign_keys'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_tasks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('router_id', sa.String(length=255), nullable=False),
    sa.Column('service', sa.String(length=64), nullable=False),
    sa.Column('task', sa.String(length=128), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('days_of_week', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('run_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_run_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_status', sa.String(length=32), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scheduled_tasks_enabled_time', 'scheduled_tasks', ['enabled', 'hour', 'minute'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_router_id'), 'scheduled_tasks', ['router_id'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_user_id'), 'scheduled_tasks', ['user_id'], unique=False)
    op.create_index('ix_scheduled_tasks_user_router', 'scheduled_tasks', ['user_id', 'router_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scheduled_tasks_user_router', table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_user_id'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_router_id'), table_name='scheduled_tasks')
    op.drop_index('ix_scheduled_tasks_enabled_time', table_name='scheduled_tasks')
    op.drop_table('scheduled_tasks')
    # ### end Alembic commands ###
