"""update_blacklist_model_structure

Revision ID: 6a63def03834
Revises: remove_router_unique
Create Date: 2025-07-31 17:52:31.780004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a63def03834'
down_revision: Union[str, None] = 'remove_router_unique'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_blacklists', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('user_blacklists', sa.Column('added_at', sa.TIMESTAMP(), nullable=True))
    op.drop_column('user_blacklists', 'reason')
    op.drop_column('user_blacklists', 'blocked_at')
    op.drop_column('user_blacklists', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_blacklists', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user_blacklists', sa.Column('blocked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user_blacklists', sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('user_blacklists', 'added_at')
    op.drop_column('user_blacklists', 'description')
    # ### end Alembic commands ###
